2022-06-03 12:30:05,676 ERROR asyncio MainThread : Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Kernel.poll_control_queue() running at C:\Users\Alexander\anaconda3\lib\site-packages\ipykernel\kernelbase.py:227> wait_for=<Future finished result=<Future at 0x...state=pending>> cb=[_chain_future.<locals>._call_set_state() at C:\Users\Alexander\anaconda3\lib\asyncio\futures.py:391]>
